name: Build and test
on: 
  workflow_call:
    inputs:
      upload-pages-artifacts:
        type: boolean
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v3
      -uses: actions/setup-checkout@v3
       with:
        node-version: 18
      -run: npm ci
      -run: npm build
      -run: npm run test:integration
      -run: npm run test:e2e
      -uses: actions/upload-artivate@v3
       with: 
        name: e2e-videos
        path: cypress/videos/
      -if: ${{ inputs.upload-pages-artifact }}
       uses: actions/upload-pages-artifact@v1
       with:
       path: build/

